include:
  project: 'sunnywalden/ci-templates'
  ref: master
  file: '/templates/.gitlab-ci-maven-template.yml'

variables:
  GIT_DEPTH: "1"
  GIT_CLEAN_FLAGS: "none"
  MYSQL_HOST: "127.0.0.1"
  MYSQL_DATABASE: "unit_test"
  MYSQL_USER: "test"
  MYSQL_PASSWORD: "123456"

static_portfolio:
  variables:
    POM_PATH: "backend/portfolio"
  extends:
    .sonarqube_job
  only:
    refs:
      - tech-unit-test
    changes:
      - backend/portfolio/*

static_top2:
  variables:
    POM_PATH: "backend/top"
  extends:
    .sonarqube_job
  only:
    refs:
      - tech-unit-test
    changes:
      - backend/top/*

build_portfolio:
  variables:
    POM_PATH: "backend/portfolio"
  extends:
    .build
  only:
    refs:
      - tech-unit-test
    changes:
      - backend/portfolio/*

build_top2:
  variables:
    POM_PATH: "backend/top"
  extends:
    .build
  only:
    refs:
      - tech-unit-test
    changes:
      - backend/top/*

test_portfolio:
  variables:
    POM_PATH: "backend/portfolio"
    APP_NAME: "portfolio"
  extends: .unit_test
  only:
    changes:
      - backend/portfolio/*
    refs:
      - tech-unit-test

test_top2:
  variables:
    POM_PATH: "backend/top"
    APP_NAME: "top"
  extends: .unit_test
  only:
    changes:
      - backend/top/*
    refs:
      - tech-unit-test

pages_portfolio:
  variables:
    POM_PATH: "backend/portfolio"
  extends: .pages
  only:
    changes:
      - backend/portfolio/*
    refs:
      - tech-unit-test

pages_top2:
  variables:
    POM_PATH: "backend/top"
  extends: .pages
  only:
    changes:
      - backend/top/*
    refs:
      - tech-unit-test


