include:
  project: 'tezign_dev/ci-templates'
  ref: master
  file: '/templates/.gitlab-ci-python-template.yml'

unit_test:
  extends:
    .unit_test
  script:
    - python manage.py makemigrations && python manage.py migrate
    - nohup python manage.py runserver &
    - pip install requests
#    - ln -s /usr/local/python3/bin/coverage /usr/bin/coverage
    - coverage run --source='account,ali_oss,qiniu_oss' manage.py test --
  after_script:
    - pip install coverage
    - ln -s /usr/local/python3/bin/coverage /usr/bin/coverage
    - coverage report
  allow_failure: true


static_analysis:
  stage: static_analysis
#  image: python:3.7
  image: tezign.com:5000/centos7-python3.7:latest
#  before_script:
#    - pip install flake8
#    - ln -s /usr/local/python3/bin/flake8 /usr/bin/flake8
  script:
    - pip install flake8
    - ln -s /usr/local/python3/bin/flake8 /usr/bin/flake8
    - flake8 --max-line-length=120 account/*.py
    - flake8 --max-line-length=120 ali_oss/*.py
    - flake8 --max-line-length=120 cmdb/*.py
  allow_failure: true


sonarqube-check:
  extends:
    .sonar_static_analysis
  variables:
    SONAR_TOKEN: $SONAR_LOGIN
    SONAR_HOST_URL: $SONAR_URL
  only:
      - merge_requests
      - branches

sonar-check:
  extends:
    .sonar_check
  variables:
    SONAR_TOKEN: $SONAR_LOGIN
    SONAR_HOST_URL: $SONAR_URL
  only:
      - merge_requests
      - branches


build_image:
  extends:
    .build_image

staging:
  variables:
    STAGING_SERVER_IP: $OPS_STAGING_SERVER_IP
  extends:
    .staging
  when: manual

production:
  variables:
    PRODUCTION_SERVER_IP: $OPS_PRODUCTION_SERVER_IP
    PRODUCTION_SERVER_USER: $OPS_PRODUCTION_SERVER_USER
  extends:
    .production
