image: tezign.com:5000/docker-with-compose:stable
services:
  - docker:dind
variables:
  GIT_DEPTH: 3
  DOCKER_DRIVER: overlay2
before_script:
  - mkdir -p /root/.ssh
  - echo "$DEPLOY_SSH_KEY" > /root/.ssh/id_rsa.pub
  - echo "$DEPLOY_SSH_PRI_KEY" > /root/.ssh/id_rsa
  - chmod -R 700 /root/.ssh
  - mkdir -p /etc/docker/certs.d/tezign.com:5000
  - |
    echo "$REGISTRY_CERT" >> /etc/docker/certs.d/tezign.com:5000/registry.crt
  - echo "10.28.204.14 tezign.com" >> /etc/hosts
  - |
    echo '{
      "registry-mirrors": [
        "https://15gvlmjd.mirror.aliyuncs.com"
      ],
      "insecure-registries": [
        "tezign.com"
      ],
      "bip":"192.169.100.1/24"
    }' >> /etc/docker/daemon.json


.test:
  image: python:3.7
  stage: test
  services:
    - name: rabbitmq:latest
      alias: ops_web_rabbitmq
    - name: redis:latest
      alias: ops_web_redis
    - name: mysql:latest
      alias: ops_web_mysql
#       command: [ '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  variables:
    TZ: Asia/Shanghai
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: tezign0818
    MYSQL_USER: tezign
    MYSQL_PASSWORD: tezign0818
    MYSQL_DATABASE: ops
    MYSQL_ROOT_PASSWORD: tezign0818
    MYSQL_HOST: ops_web_mysql
    MYSQL_PORT: 3306
  script:
    - coverage run manage.py test
    - coverage report --include=*/tests/test*
  allow_failure: true

.build:
  stage: build_image
  image:
    name: tezign.com:5000/kaniko-executor:debug
    entrypoint: [""]
  before_script:
    - |
      echo "
      {
        "auths":
          {
            "$CI_REGISTRY":
              {
                "username": "$CI_REGISTRY_USER",
                "password": "$CI_REGISTRY_PASSWORD"
              }
          },
      }" > /kaniko/.docker/config.json
    - |
      echo "$REGISTRY_CERT" >> /kaniko/ssl/certs/ca-certificates.crt
    - echo "10.28.204.14 tezign.com" >> /etc/hosts
    - |
      echo '{
        "registry-mirrors": [
        "https://15gvlmjd.mirror.aliyuncs.com"
        ],
        "insecure-registries": [
          "tezign.com"
        ],
        "bip":"192.168.0.1/24"
      }' >> /kaniko/.docker/daemon.json
  script:
    - echo "image $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - if [[ $CI_COMMIT_TAG ]] && [[ $CI_COMMIT_TAG != "latest" ]];then /kaniko/executor --context $(pwd)/$CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --skip-tls-verify-registry $CI_REGISTRY;fi
    - /kaniko/executor --context $(pwd)/$CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest --skip-tls-verify-registry $CI_REGISTRY
  only:
    refs:
      - renew

stages:
  - test
  - build_image
