image: maven:3.6.2-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s /root/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
  POM_PATH: "backend/user"
  GIT_DEPTH: "3"

cache:
  paths:
    - /root/.m2/repository/
    - $POM_PATH/target/

before_script:
  - pwd
  - |
    echo '<?xml version="1.0" encoding="UTF-8"?>
          <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
              <servers>
                  <server>
                      <username>admin</username>
                      <password>APAK1MQcXFpiDLyP</password>
                      <id>central</id>
                  </server>
                  <server>
                      <username>admin</username>
                      <password>APAK1MQcXFpiDLyP</password>
                      <id>snapshots</id>
                  </server>
              </servers>
              <profiles>
                  <profile>
                      <repositories>
                          <repository>
                              <snapshots>
                                  <enabled>false</enabled>
                              </snapshots>
                              <id>central</id>
                              <name>libs-release</name>
                              <url>http://10.28.204.14:9099/artifactory/libs-release</url>
                          </repository>
                          <repository>
                              <id>snapshots</id>
                              <name>libs-snapshot</name>
                              <url>http://10.28.204.14:9099/artifactory/libs-snapshot</url>
                              <snapshots>
                                  <enabled>true</enabled>
                                  <updatePolicy>always</updatePolicy>
                              </snapshots>
                          </repository>
                      </repositories>
                      <pluginRepositories>
                          <pluginRepository>
                              <snapshots>
                                  <enabled>false</enabled>
                              </snapshots>
                              <id>central</id>
                              <name>libs-release</name>
                              <url>http://10.28.204.14:9099/artifactory/libs-release</url>
                          </pluginRepository>
                          <pluginRepository>
                              <snapshots />
                              <id>snapshots</id>
                              <name>libs-snapshot</name>
                              <url>http://10.28.204.14:9099/artifactory/libs-snapshot</url>
                          </pluginRepository>
                      </pluginRepositories>
                      <id>artifactory</id>
                  </profile>
              </profiles>
              <activeProfiles>
                  <activeProfile>artifactory</activeProfile>
              </activeProfiles>

          </settings>' > /root/.m2/settings.xml

.build:
  stage: build
  variables:
    POM_PATH: "backend/user"
  script:
    - mvn clean -f $POM_PATH/pom.xml $MAVEN_CLI_OPTS compile
  only:
    refs:
      - tech-4.2.0
      - master
      - merge_requests
      - tags
    changes:
      - backend/user/*


.test:
  stage: test
  variables:
    POM_PATH: "backend/user"
  script:
    - mvn clean $MAVEN_CLI_OPTS -f $POM_PATH/pom.xml test
    - cat $POM_PATH/target/site/jacoco/index.html
  after_script:
    - echo "AUto CI finished"
  only:
    changes:
      - backend/user/*
    refs:
      - tech-4.2.0
      - merge_requests
      - master
      - tags
  allow_failure: true

.stages:
 - build
 - test
# - deploy